name: React CI with Vite and PM2

on:
  push:
    branches: [ "dev" ]
  pull_request_target:
    branches: [ "dev" ]

jobs:
  build:
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.12.0]

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Set up Node.js
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # Ensure Bun is Installed
    - name: Ensure Bun is Installed
      run: |
        if ! command -v bun &> /dev/null; then
          echo "Installing Bun..."
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
          echo "export PATH=$HOME/.bun/bin:\$PATH" >> $HOME/.bashrc
        fi
        export PATH=$HOME/.bun/bin:$PATH
        bun --version

    # Ensure PM2 is Installed
    - name: Ensure PM2 is Installed
      run: |
        if ! command -v pm2 &> /dev/null; then
          echo "Installing PM2..."
          npm install -g pm2
          echo "$(npm bin -g)" >> $GITHUB_PATH
        fi
        pm2 --version

    # Debug Directory Structure
    - name: Debug Directory Structure
      run: |
        echo "Checking root directory..."
        ls -la
        echo "Checking index.html in the root folder..."
        if [ ! -f index.html ]; then
          echo "Error: index.html is missing in the root folder."
          exit 1
        else
          echo "index.html exists in the root folder."
        fi

    # Move index.html to public folder (React-Scripts Requirement)
    - name: Move index.html to Public Directory
      run: |
        echo "Moving index.html to public directory..."
        mkdir -p public
        mv index.html public/index.html

    # Install Dependencies
    - name: Install Dependencies
      run: |
        export PATH=$HOME/.bun/bin:$PATH
        rm -rf node_modules dist build # Clean old builds
        bun install || npm install

    # Build the React App
    - name: Build React App
      run: |
        export PATH=$HOME/.bun/bin:$PATH
        echo "Building the React app..."
        bun run build || npm run build

    # Restart Application with PM2
    - name: Restart React App with PM2
      run: |
        export PATH=$HOME/.bun/bin:$PATH
        echo "Restarting React application with PM2..."
        pm2 delete kwickbill-ui-dev || true
        pm2 start serve --name kwickbill-ui-dev -- -s dist -l 5177 || pm2 restart kwickbill-ui-dev --update-env
        pm2 save
        pm2 list
