name: React CI with Vite and PM2

on:
  push:
    branches: ["stage"]
  pull_request_target:
    branches: ["stage"]

jobs:
  build:
    if: github.ref == 'refs/heads/stage'
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.12.0]

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Set up Node.js
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # Step 3: Ensure Bun is Installed
    - name: Ensure Bun is Installed
      run: |
        if ! command -v bun &> /dev/null; then
          echo "Installing Bun..."
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
          echo "export PATH=$HOME/.bun/bin:\$PATH" >> $HOME/.bashrc
        fi
        export PATH=$HOME/.bun/bin:$PATH
        bun --version

    # Step 4: Ensure PM2 is Installed
    - name: Ensure PM2 is Installed
      run: |
        if ! command -v pm2 &> /dev/null; then
          echo "Installing PM2..."
          npm install -g pm2
          echo "$(npm bin -g)" >> $GITHUB_PATH
        fi
        pm2 --version

    # Step 5: Install Dependencies
    - name: Install Dependencies
      run: |
        export PATH=$HOME/.bun/bin:$PATH
        bun install || npm install

    # Step 6: Build the React App with Vite
    - name: Build React App
      run: |
        export PATH=$HOME/.bun/bin:$PATH
        bun run build || npm run build

    # Step 7: Restart Application with PM2
    - name: Restart React App with PM2
      run: |
        echo "Restarting React application with PM2..."
        # Delete the existing process if it exists
        if pm2 describe kwickbill-ui-stage > /dev/null; then
          pm2 delete kwickbill-ui-stage
        fi
        # Start the application with the correct folder and port
        pm2 start serve --name kwickbill-ui-stage -- -s stage-dist -l 5174
        # Save the PM2 process list
        pm2 save
        # List all PM2 processes
        pm2 list
