name: React Build Workflow with Bun and Vite

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Bun
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      # Step 3: Install dependencies using Bun
      - name: Install Dependencies
        run: bun install

      # Step 4: Build the project based on the branch
      - name: Build Application
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            bun run build:main
          elif [ "${{ github.ref_name }}" == "dev" ]; then
            bun run build:dev
          fi

      # Step 5: Upload build artifact (Optional)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ github.ref_name }}
          path: |
            build-main
            build-dev
