name: React CI with Vite and PM2

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x, 18.x] # Use appropriate Node.js versions

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Set up Node.js
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # Ensure PM2 is Installed
    - name: Ensure PM2 is Installed
      run: |
        if ! command -v pm2 &> /dev/null; then
          echo "Installing PM2..."
          npm install -g pm2
        fi
        pm2 --version

    # Install Dependencies
    - name: Install Dependencies
      run: |
        npm ci

    # Build the React App with Vite
    - name: Build React App
      run: |
        npm run build

    # Deploy React App with PM2
    - name: Deploy with PM2
      run: |
        echo "Deploying React application with PM2..."
        APP_NAME="kwickbill-ui-prod"
        DIST_DIR="dist"
        PORT=5173
        # Delete existing PM2 process if it exists
        pm2 delete $APP_NAME || echo "No existing process found. Proceeding with deployment..."
        # Start or restart the app
        pm2 start serve --name $APP_NAME -- -s $DIST_DIR -l $PORT
        # Save the PM2 configuration
        pm2 save
        # Display PM2 process list
        pm2 list
