name: React Build Workflow with Bun and Vite

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Bun
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      # Step 3: Install dependencies using Bun
      - name: Install Dependencies
        run: bun install

      # Step 4: Build the project based on the branch
      - name: Build Application
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            bun run build:main
          elif [ "${{ github.ref_name }}" == "dev" ]; then
            bun run build:dev
          fi

      # Step 5: Upload build artifact (Optional)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ github.ref_name }}
          path: |
            build-main
            build-dev
            
    # Restart Application with PM2
      - name: Restart React App with PM2
        run: |
          echo "Restarting React application with PM2..."
          # Delete the existing process if it exists
          pm2 delete kwickbill-ui-prod || echo "Process kwickbill-ui-prod not found, skipping delete step."
          # Start or restart the application
          pm2 start serve --name kwickbill-ui-prod -- -s dist -l 5173 || pm2 restart kwickbill-ui-prod --update-env
          # Save the PM2 process list
          pm2 save
          # List all PM2 processes
          pm2 list

            
