name: React CI with Vite and PM2

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.12.0]

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Ensure Bun is Installed
      - name: Ensure Bun is Installed
        run: |
          if ! command -v bun &> /dev/null; then
            echo "Installing Bun..."
            curl -fsSL https://bun.sh/install | bash
            echo "$HOME/.bun/bin" >> $GITHUB_PATH
            echo "export PATH=$HOME/.bun/bin:\$PATH" >> $HOME/.bashrc
          fi
          export PATH=$HOME/.bun/bin:$PATH
          bun --version

      # Ensure PM2 is Installed
      - name: Ensure PM2 is Installed
        run: |
          if ! command -v pm2 &> /dev/null; then
            echo "Installing PM2..."
            npm install -g pm2
            echo "$(npm bin -g)" >> $GITHUB_PATH
          fi
          pm2 --version

      # Install Dependencies
      - name: Install Dependencies
        run: |
          export PATH=$HOME/.bun/bin:$PATH
          bun install || npm install

      # Build the React App with Vite
      - name: Build React App
        run: |
          export PATH=$HOME/.bun/bin:$PATH
          bun run build:main

      # Upload Build Artifact (Optional)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-main
          path: build-main

      # Serve the React App with PM2
      - name: Serve React App with PM2
        run: |
          echo "Serving React application with PM2..."
          # Delete existing PM2 process if any
          pm2 delete kwickbill-ui-prod || echo "Process kwickbill-ui-prod not found, skipping delete step."
          # Start or restart the application
          pm2 start serve --name kwickbill-ui-prod -- -s build-main -l 5173
          pm2 save
          pm2 list
